version: "3.9"

services:

  webserver:
    container_name: 'NGINX'
    image: "nginx:1.22.1"
    restart: 'always'
    volumes:
      - webserver_storage:/var/www/html:ro
    # networks:
    #   frontend:
    #     ipv4_address: "172.16.10.22
    ports:
      - "8600:80"
      # - "8443:443"

  backend:
    container_name: 'FastAPI'
    image: backend
    build: 
      context: backend
      dockerfile: backend.Dockerfile
    restart: 'always'
    environment:
      APPLICATION: "${APPLICATION}"
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_DATABASE: "${DB_DATABASE}"
    # networks:
    #   frontend:
    #     ipv4_address: "${APP_HOST}"
    ports:
      - "8800:8000"

  database:
    container_name: 'MariaDB'
    image: "mariadb:10.9.3"
    restart: 'always'
    volumes: 
      - "database_storage:/var/lib/mysql"
      - "./database/:/docker-entrypoint-initdb.d/:ro"
    environment:
      MARIADB_ROOT_PASSWORD: 'insecure'
      MYSQL_ROOT_PASSWORD: 'insecure'
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    # networks:
    #   backend:
    #     ipv4_address: "${DB_HOST}"
    ports:
      - "8900:3306"
    
volumes:
  database_storage:
    driver: local
  webserver_storage:
    driver: local
  backend_storage:
    driver: local

# networks:
#   backend:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.16.20.0/24
#           gateway: 172.16.20.1
#   frontend:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.16.10.0/24
#           gateway: 172.16.10.1