version: "3.9"

services:

  webserver:
    container_name: 'NGINX'
    hostname: 'webserver01'
    image: "nginx:${NGINX_VERSION}"
    restart: 'always'
    volumes:
      - "webserver_storage:/var/www/html"
      - "./frontend/build/:/var/www/html:ro"
      - "./linux/nginx/:/etc/nginx/conf.d/:ro"
    networks:
      frontend:
        ipv4_address: "172.16.10.22"
    ports:
      - "80:80"
      # - "8443:443"

  backend:
    container_name: 'FastAPI'
    hostname: 'backend01'
    build:
      context: .
      dockerfile: ./backend.Dockerfile
    image: backend
    restart: 'always'
    volumes:
      - "backend_storage:/fastapi"
    environment:
      APPLICATION: "${APPLICATION}"
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_DATABASE: "${DB_DATABASE}"
    networks:
      backend:
        ipv4_address: "${APP_HOST}"
    ports:
      - "8000:8000"

  database:
    container_name: 'MariaDB'
    hostname: 'database01'
    image: "mariadb:${MARIADB_VERSION}"
    restart: 'always'
    volumes: 
      - "database_storage:/var/lib/mysql"
      - "./database/:/docker-entrypoint-initdb.d/:ro"
    environment:
      MARIADB_ROOT_PASSWORD: DB_PASSWORD_ROOT
      MYSQL_ROOT_PASSWORD: DB_PASSWORD_ROOT
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      backend:
        ipv4_address: "${DB_HOST}"
    ports:
      - "3306:3306"
    
volumes:
  database_storage:
    driver: local
  webserver_storage:
    driver: local
  backend_storage:
    driver: local

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.20.0/24
          gateway: 172.16.20.1
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.10.0/24
          gateway: 172.16.10.1