version: "3.9"

services:
  # webserver:
  #   container_name: 'E_ngnix'

  database:
    container_name: 'M_ariadb'
    image: "mariadb:latest"
    restart: 'always'
    volumes: 
      - "database:/var/lib/mysql"
      - "./lemp.sql:/docker-entrypoint-initdb.d/lemp.sql:ro"
    environment:
      MARIADB_ROOT_PASSWORD: 'insecure'
      MYSQL_ROOT_PASSWORD: 'insecure'
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    # networks:
    #   backend:
    #     ipv4_address: "${DB_HOST}"
    ports:
      - "${DB_PORT}:3306"
    
volumes:
  database:
    driver: local

# networks:
#   backend:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.16.20.0/24
#           gateway: 172.16.20.1
#   frontend:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.16.10.0/24
#           gateway: 172.16.10.1