CREATE DATABASE lemp;

USE lemp;
CREATE TABLE messages (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    sender NOT NULL VARCHAR(255),
    text TEXT
);

CREATE USER 'lemp'@'localhost' IDENTIFIED BY 'lemp';
GRANT ALL PRIVILEGES ON *.* TO 'lemp'@'localhost' WITH GRANT OPTION;
CREATE USER 'lemp'@'%' IDENTIFIED BY 'lemp';
GRANT ALL PRIVILEGES ON *.* TO 'lemp'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;