---

- name: Install LEMP Stack (Ubuntu)
  hosts: localhost
  remote_user: bryan
  become: true

  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name:
          - python3.10
          - python3-pip
          - nginx
          - mariadb-server
        state: present

...
